leftnav:
- identifier: 5bb748d7-5756-4859-98f0-a4425ab162db
  name: page
  url: /pages/pagw
  weight: 10
- identifier: 5d9e5d3a-6e87-42b6-a0a5-f1a35c76a3fe
  name: page control
  url: /resources/site19-test4
  weight: 20
